import "./globals.css";
import React, { ReactNode, useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation/Navigation";
import SideNavbar from "@/components/Navigation/SideNavbar";
import { SessionProvider } from "next-auth/react";
import { AuthProvider } from "./Providers";
import { Toaster } from "react-hot-toast";
import MainNavigation from "@/components/MainNavigation";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin - DRT ADJUSTING",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/img/companyMetaData.png",
        width: 1920,
        height: 1080,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={`/img/companyFavicon.png`} />

      <body
        className={`bg-[#F1F1F1] bg-cover bg-no-repeat relative ${inter.className}`}
      >
        <AuthProvider>
          <MainNavigation>{children}</MainNavigation>
        </AuthProvider>
      </body>
    </html>
  );
}
