"use client";
import "./globals.css";
import React, { ReactNode, useState } from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation/Navigation";
import SideNavbar from "@/components/Navigation/SideNavbar";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin - DRT ADJUSTING",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/img/companyMetaData.png",
        width: 1920,
        height: 1080,
      },
    ],
  },
};

export default function RootLayout({
  children,
  session,
}: {
  children: React.ReactNode;
  session: any;
}) {
  const [sidebarOpen, setSidebarOpen] = useState(true);

  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={`/img/companyFavicon.png`} />
      <SessionProvider session={session}>
        <body
          className={`bg-[#F1F1F1] bg-cover bg-no-repeat relative ${inter.className}`}
        >
          <Navigation
            setSidebarOpen={setSidebarOpen}
            sidebarOpen={sidebarOpen}
          />
          <div className="pt-[95px] lg:pt-[135px] flex">
            <SideNavbar
              sidebarOpen={sidebarOpen}
              setSidebarOpen={setSidebarOpen}
            />

            <div className="lg:ps-96">{children}</div>
          </div>
        </body>
      </SessionProvider>
    </html>
  );
}
