import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation/Navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Admin - DRT ADJUSTING",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/img/companyMetaData.png",
        width: 1920,
        height: 1080,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <link rel="icon" type="image/x-icon" href={`/img/companyFavicon.png`} />
      <body
        className={`bg-[url('/img/HeroImage.png')] bg-cover bg-no-repeat ${inter.className}`}
      >
        <Navigation />
        <div className="pt-[95px] md:pt-[135px]">{children}</div>
      </body>
    </html>
  );
}
