import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DRT ADJUSTING",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "/img/companyMetaData.png",
        width: 1920,
        height: 1080,
      },
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.className}  scroll-smooth scroll-pt-32`}
    >
      <link rel="icon" type="image/x-icon" href={`/img/company-favicon.png`} />
      <body>
        <Navigation />
        <div className="pt-[95px] md:pt-[135px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
